[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 18

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
opacity = 0.6

[window.dimensions]
columns = 90
lines = 17

# colors: old theme from yaml (Unknown)
    # primary:
        # background: '#2e3440'
        # foreground: '#aaacb1'
    # normal:
        # black: '#474f55'
        # red: '#8d8f90'
        # green: '#a6aaa6'
        # yellow: '#aba9b3'
        # blue: '#b5b9be'
        # magenta: '#bcbcc2'
        # cyan: '#676d7e'
        # white: '#ccd1d1'
