#!/bin/bash

case $1 in
alacritty) alacritty --working-directory ~ ;;
atril) atril ;;
mpv) mpv ;;
gedit) gedit ;;
falkon) falkon ;;
thunar) thunar ~ ;;
qview) qview ;;
timeshift-launcher) timeshift-launcher ;;
appbar) ./appbar ;;
esac
